name: Push Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'commit/qa/**'
      - 'commit/prod/**'

jobs:
  detect_apis:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changed APIs and build matrix
        id: set-matrix
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^commit/' | grep -E '/(properties|service)\.yml$')
          MATRIX="["
          SEP=""
          for FILE in $CHANGED_FILES; do
            ENV_NAME=$(echo "$FILE" | cut -d'/' -f2)
            TEAM_NAME=$(echo "$FILE" | cut -d'/' -f3)
            API_NAME=$(echo "$FILE" | cut -d'/' -f4)
            # Only add if API_NAME is not empty
            if [ -n "$API_NAME" ]; then
              MATRIX="${MATRIX}${SEP}{\"env_name\":\"$ENV_NAME\",\"team_name\":\"$TEAM_NAME\",\"api_name\":\"$API_NAME\"}"
              SEP="," 
            fi
          done
          MATRIX="${MATRIX}]"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  call_api_deploy:
    needs: detect_apis
    if: needs.detect_apis.outputs.matrix != '[]'
    strategy:
      max-parallel:1
      matrix:
        include: ${{ fromJson(needs.detect_apis.outputs.matrix) }}
    uses: ./.github/workflows/api-deploy.yml
    with:
      env_name: ${{ matrix.env_name }}
      team_name: ${{ matrix.team_name }}
      api_name: ${{ matrix.api_name }}
