name: Push Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'commit/qa/**'
      - 'commit/prod/**'

jobs:
  detect_apis:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --tags --all

      - name: Detect changed APIs and build matrix
        id: set-matrix
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^commit/' | grep -E '/(properties|service)\.yml$')
          MATRIX="[
          SEP=""
          for FILE in $CHANGED_FILES; do
            ENV_NAME=$(echo "$FILE" | cut -d'/' -f2)
            TEAM_NAME=$(echo "$FILE" | cut -d'/' -f3)
            API_NAME=$(echo "$FILE" | cut -d'/' -f4)
            # Only add if API_NAME is not empty
            if [ -n "$API_NAME" ]; then
              MATRIX="${MATRIX}${SEP}{\"env_name\":\"$ENV_NAME\",\"team_name\":\"$TEAM_NAME\",\"api_name\":\"$API_NAME\"}"
              SEP="," 
            fi
          done
          MATRIX="${MATRIX}]"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  call_api_deploy:
    needs: detect_apis
    runs-on: ubuntu-latest
    if: needs.detect_apis.outputs.matrix != '[]'
    strategy:
      matrix:
        include: ${{ fromJson(needs.detect_apis.outputs.matrix) }}
    steps:
      - name: Trigger API Deploy Workflow
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'api-deploy.yml',
              ref: context.ref,
              inputs: {
                env_name: '${{ matrix.env_name }}',
                team_name: '${{ matrix.team_name }}',
                api_name: '${{ matrix.api_name }}'
              }
            })
